# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Once < Formula
  desc "Safely run commands concurrently that do not support it natively"
  homepage "https://github.com/jaredallard/once"
  version "0.2.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaredallard/once/releases/download/v0.2.1/once_0.2.1_darwin_amd64.tar.gz"
      sha256 "74cd4d33e9925cf335153bf3a7ec5c390a199a09a8c0f220b62359e79073cd05"

      def install
        bin.install "once"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaredallard/once/releases/download/v0.2.1/once_0.2.1_darwin_arm64.tar.gz"
      sha256 "7df7dd7e735f042c401972e7007a9976cf08a7329b2c7aaf5b0db5ce4e3cc44e"

      def install
        bin.install "once"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaredallard/once/releases/download/v0.2.1/once_0.2.1_linux_amd64.tar.gz"
      sha256 "44bb74210653e80c34f650ced6eebb4bf5380bf65591e6ab77a6fa5f4137625a"
      def install
        bin.install "once"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jaredallard/once/releases/download/v0.2.1/once_0.2.1_linux_arm64.tar.gz"
      sha256 "dd39444c758632f0bd711250bad64127c5e917f31a925ffbefbf2db4c75591ed"
      def install
        bin.install "once"
      end
    end
  end
end
