# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Once < Formula
  desc "Safely run commands concurrently that do not support it natively"
  homepage "https://github.com/jaredallard/once"
  version "0.2.3"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaredallard/once/releases/download/v0.2.3/once_0.2.3_darwin_amd64.tar.gz"
      sha256 "b1da30d2389dfaf17e3501f73986213e07a68b8790be1dc7f83b290011ad72fe"

      def install
        bin.install "once"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaredallard/once/releases/download/v0.2.3/once_0.2.3_darwin_arm64.tar.gz"
      sha256 "035eecabc2fa3800a5ca15c601737673677ef577db8a701c4bf79d05d2af1b2b"

      def install
        bin.install "once"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredallard/once/releases/download/v0.2.3/once_0.2.3_linux_amd64.tar.gz"
      sha256 "840247e1f30ed21623ce079af99725d04d8dbbbe23c86c787e637e211ec47e01"
      def install
        bin.install "once"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaredallard/once/releases/download/v0.2.3/once_0.2.3_linux_arm64.tar.gz"
      sha256 "516f8b2956d0acc06009408e35973713d156b6d4b7750a1fe52ac6d702497f22"
      def install
        bin.install "once"
      end
    end
  end
end
