# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remarkabledayone < Formula
  desc "A utility to sync pages from a Remarkable 2 tablet to Day One"
  homepage "https://github.com/jaredallard/remarkabledayone"
  version "0.1.4"
  license "AGPL-3.0"

  depends_on "imagemagick"

  on_macos do
    on_intel do
      url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.4/remarkabledayone_0.1.4_darwin_amd64.tar.xz"
      sha256 "553ae2544535e6113f352a6ca39123ae5c9396ab052fd31597cdd69d8dabe918"

      def install
        bin.install "remarkabledayone"
      end
    end
    on_arm do
      url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.4/remarkabledayone_0.1.4_darwin_arm64.tar.xz"
      sha256 "eb8d2057bafb7b8c051ad19723e8339d741de649a1607d7bdd033f7cb04446a8"

      def install
        bin.install "remarkabledayone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.4/remarkabledayone_0.1.4_linux_amd64.tar.xz"
        sha256 "4b1701112b011532485d98a0d43028e363f07d41ff857202d65ea69c7b4707f5"

        def install
          bin.install "remarkabledayone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.4/remarkabledayone_0.1.4_linux_arm64.tar.xz"
        sha256 "acd92f1381bb337d000063b065282b49c3a0ba7c12707a078c28dab7d5d68b42"

        def install
          bin.install "remarkabledayone"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Dayone must be installed manually from the app store.
      Inkscape must be installed manually via `brew install --cask inkscape`.
    EOS
  end
end
