# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Remarkabledayone < Formula
  desc "A utility to sync pages from a Remarkable 2 tablet to Day One"
  homepage "https://github.com/jaredallard/remarkabledayone"
  version "0.1.3"
  license "AGPL-3.0"

  depends_on "imagemagick"
  depends_on "inkscape"

  on_macos do
    on_intel do
      url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.3/remarkabledayone_0.1.3_darwin_amd64.tar.xz"
      sha256 "be80b5bc4cd3b7e07ab52f635fc90237a75ae766c8dcd2430defe76c0a184adc"

      def install
        bin.install "remarkabledayone"
      end
    end
    on_arm do
      url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.3/remarkabledayone_0.1.3_darwin_arm64.tar.xz"
      sha256 "895ed31e34288b6fc6ee96a4827c16bb53d1174dfc7118d602c161d74e4f4e89"

      def install
        bin.install "remarkabledayone"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.3/remarkabledayone_0.1.3_linux_amd64.tar.xz"
        sha256 "faf4317841c3b741fee21e4b2a40ac2b26c027aecb0986d2d4b3d0783d8cda64"

        def install
          bin.install "remarkabledayone"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jaredallard/remarkabledayone/releases/download/v0.1.3/remarkabledayone_0.1.3_linux_arm64.tar.xz"
        sha256 "85135c964a7e78f250627224dadc5a3cebc2201f8f42b83aa9421de1bfbefa8f"

        def install
          bin.install "remarkabledayone"
        end
      end
    end
  end
end
